# Generated by Django 3.0.4 on 2020-03-29 23:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_barcode', models.CharField(max_length=13, null=True, unique=True)),
                ('local_barcode_image', models.ImageField(null=True, upload_to='')),
                ('admitted_at', models.DateTimeField(default=None, null=True)),
                ('admitted', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='submission.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('equip fail', 'Equipment failure'), ('unavailable', 'Unavailable')], max_length=20, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Out of service'), (1, 'Assigned'), (2, 'Available')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('breathing_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('gcs_eye', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='GCS eye')),
                ('gcs_verbal', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='GCS verbal')),
                ('gcs_motor', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='GCS motor')),
                ('observations', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('WHITE', 'White')], max_length=6)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_snapshots', to='patient_tracker.Admission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discharged_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_events', to='patient_tracker.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patient_tracker.Admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patient_tracker.Bed')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='admissions',
            field=models.ManyToManyField(related_name='assigned_beds', through='patient_tracker.BedAssignment', to='patient_tracker.Admission'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='patient_tracker.BedType'),
        ),
        migrations.CreateModel(
            name='HealthSnapshotProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Health Snapshot',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patient_tracker.healthsnapshot',),
        ),
    ]
