# Generated by Django 3.0.5 on 2020-04-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthsnapshot',
            name='user',
        ),
    ]
