# Generated by Django 3.0.5 on 2020-04-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_patient_id', models.CharField(default=None, max_length=12, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient_tracker.Patient'),
        ),
    ]
