# Generated by Django 3.0.4 on 2020-04-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_tracker', '0002_auto_20200404_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notified_next_of_kin', models.BooleanField(default=False)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='patient_tracker.Admission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_deceased', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
