# Generated by Django 3.0.5 on 2020-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0002_auto_20200404_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedtype',
            name='severity_match',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green')], max_length=6),
        ),
    ]
