# Generated by Django 3.0.4 on 2020-03-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0002_auto_20200328_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedbed',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient_tracker.Admission'),
        ),
    ]
