# Generated by Django 3.0.5 on 2020-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0002_healthsnapshot_main_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='modifier',
        ),
        migrations.AddField(
            model_name='admission',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalAdmission',
        ),
    ]
