# Generated by Django 3.0.4 on 2020-04-04 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0003_auto_20200404_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deceased',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deceased_event', to='patient_tracker.Admission'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='registered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
