# Generated by Django 3.0.5 on 2020-04-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0003_bedtype_severity_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patient_tracker.Patient'),
        ),
    ]
