# Generated by Django 3.0.5 on 2020-04-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_historicalnextofkincontact_historicalpatient_historicalpatientphoto_historicalpersonaldata_historica'),
        ('patient_tracker', '0003_historicaladmission_historicalcommonsymptoms_historicalgradedsymptoms_historicaloverallwellbeing_his'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patient.Patient'),
        ),
    ]
