# Generated by Django 3.0.4 on 2020-03-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0003_auto_20200328_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedbed',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bed', to='patient_tracker.Admission'),
        ),
    ]
