# Generated by Django 3.0.6 on 2020-05-17 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200422_2010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_tracker', '0003_auto_20200504_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='admission',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalAdmission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('local_barcode', models.CharField(db_index=True, max_length=13, null=True)),
                ('local_barcode_image', models.TextField(max_length=100, null=True)),
                ('admitted_at', models.DateTimeField(default=None, null=True)),
                ('admitted', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patient.Patient')),
            ],
            options={
                'verbose_name': 'historical admission',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
