# Generated by Django 3.0.4 on 2020-04-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0004_auto_20200404_1341'),
        ('patient_tracker', '0004_auto_20200404_1508'),
    ]

    operations = [
    ]
