# Generated by Django 3.0.4 on 2020-03-28 22:59

from django.db import migrations, models
import django.db.models.deletion
import patient_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0005_auto_20200328_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='local_barcode',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignedbed',
            name='bed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bed_types', to='patient_tracker.BedType'),
        ),
    ]
