# Generated by Django 3.0.4 on 2020-04-04 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0005_merge_20200404_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSnapshotFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='health_snapshot_file')),
                ('notes', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshot_files', to='patient_tracker.HealthSnapshot')),
            ],
        ),
    ]
