# Generated by Django 3.0.4 on 2020-03-28 23:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0006_auto_20200328_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discharged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='admitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='patient_tracker.BedType')),
            ],
        ),
    ]
