# Generated by Django 3.0.4 on 2020-03-29 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_delete_admission'),
        ('patient_tracker', '0006_auto_20200328_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('equip fail', 'Equipment failure'), ('unavailable', 'Unavailable'), ('other', 'Other')], max_length=20, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Out of service'), (1, 'Assigned'), (2, 'Available')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discharged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='outofservicebed',
            name='bed_type',
        ),
        migrations.AddField(
            model_name='admission',
            name='admitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 29, 11, 56, 8, 798983, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='submission.Patient'),
        ),
        migrations.DeleteModel(
            name='AssignedBed',
        ),
        migrations.DeleteModel(
            name='OutOfServiceBed',
        ),
        migrations.AddField(
            model_name='discharge',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_events', to='patient_tracker.Admission'),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patient_tracker.Admission'),
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patient_tracker.Bed'),
        ),
        migrations.AddField(
            model_name='bed',
            name='admissions',
            field=models.ManyToManyField(related_name='assigned_beds', through='patient_tracker.BedAssignment', to='patient_tracker.Admission'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='patient_tracker.BedType'),
        ),
    ]
