# Generated by Django 3.0.4 on 2020-03-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0007_auto_20200328_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='admission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_events', to='patient_tracker.Admission'),
            preserve_default=False,
        ),
    ]
