# Generated by Django 3.0.4 on 2020-03-29 17:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_tracker', '0007_auto_20200329_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterField(
            model_name='bed',
            name='reason',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('equip fail', 'Equipment failure'), ('unavailable', 'Unavailable')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField()),
                ('blood_pressure_diastolic', models.PositiveIntegerField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('breathing_rate', models.PositiveIntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_saturation', models.PositiveIntegerField()),
                ('gcs_eye', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('gcs_verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gcs_motor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('observations', models.TextField()),
                ('severity', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green')], max_length=6)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_snapshot', to='patient_tracker.Admission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
