# Generated by Django 3.0.4 on 2020-03-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0008_discharge_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedbed',
            name='admission',
        ),
        migrations.AddField(
            model_name='bed',
            name='reason',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('equip fail', 'Equipment failure'), ('unavailable', 'Unavailable'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Out of service'), (1, 'Assigned'), (2, 'Available')], default=2),
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patient_tracker.Admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patient_tracker.Bed')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='admissions',
            field=models.ManyToManyField(related_name='assigned_beds', through='patient_tracker.BedAssignment', to='patient_tracker.Admission'),
        ),
    ]
