# Generated by Django 3.0.4 on 2020-03-29 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0008_auto_20200329_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSnapshotProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Health Snapshot',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patient_tracker.healthsnapshot',),
        ),
        migrations.AlterModelOptions(
            name='healthsnapshot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_snapshots', to='patient_tracker.Admission'),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='breathing_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='gcs_eye',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='GCS eye'),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='gcs_motor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='GCS motor'),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='gcs_verbal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='GCS verbal'),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
