# Generated by Django 3.0.4 on 2020-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0009_auto_20200329_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsnapshot',
            name='severity',
            field=models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('WHITE', 'White')], max_length=6),
        ),
    ]
