# Generated by Django 3.0.4 on 2020-03-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0009_auto_20200329_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outofservicebed',
            name='bed_type',
        ),
        migrations.DeleteModel(
            name='AssignedBed',
        ),
        migrations.DeleteModel(
            name='OutOfServiceBed',
        ),
    ]
