# Generated by Django 3.0.4 on 2020-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0009_auto_20200329_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admitted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='local_barcode_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admitted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='local_barcode',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
