# Generated by Django 3.0.4 on 2020-03-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0010_auto_20200329_2022'),
        ('patient_tracker', '0010_auto_20200329_1938'),
    ]

    operations = [
    ]
