# Generated by Django 3.0.4 on 2020-03-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0011_merge_20200329_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admitted',
            field=models.BooleanField(default=True),
        ),
    ]
