# Generated by Django 3.0.4 on 2020-03-29 23:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenterAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_patient_id', models.CharField(default=None, max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('id_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submission.Patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heart_condition', models.BooleanField(default=False)),
                ('high_blood_pressure', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('chronic_lung_problems', models.BooleanField(default=False)),
                ('mild_diabetes', models.BooleanField(default=False)),
                ('chronic_diabetes', models.BooleanField(default=False)),
                ('current_chemo', models.BooleanField(default=False)),
                ('past_chemo', models.BooleanField(default=False)),
                ('take_immunosuppressants', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_conditions', to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=50)),
                ('phone_type', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Prefer not to disclose')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='OverallWellbeing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_wellbeing', to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='GradedSymptoms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_breathing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('anxious', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graded_symptoms', to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='CommonSymptoms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chills', models.BooleanField(default=False)),
                ('achy_joints_muscles', models.BooleanField(default=False)),
                ('lost_taste_smell', models.BooleanField(default=False)),
                ('congestion', models.BooleanField(default=False)),
                ('stomach_disturbance', models.BooleanField(default=False)),
                ('tiredness', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('dry_cough', models.BooleanField(default=False)),
                ('cough_with_sputum', models.BooleanField(default=False)),
                ('nauseous', models.BooleanField(default=False)),
                ('short_of_breath', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('runny_nose', models.BooleanField(default=False)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_symptoms', to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='ChosenMedicalCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_center', to='submission.MedicalCenter')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_medical_center', to='submission.Submission')),
            ],
        ),
    ]
