# Generated by Django 3.0.4 on 2020-03-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='master_id',
            new_name='master',
        ),
    ]
