# Generated by Django 3.0.5 on 2020-04-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_tracker', '0002_auto_20200404_0929'),
        ('submission', '0002_initialhealthsnapshot_initialhealthsnapshotinline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='patient_tracker.Patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
