# Generated by Django 3.0.4 on 2020-03-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200328_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='submission.Submission'),
        ),
        migrations.AlterField(
            model_name='person',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='submission.Submission'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='submission.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submission.Master'),
        ),
    ]
