# Generated by Django 3.0.4 on 2020-04-04 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20200404_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKinContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('WIFE', 'Wife'), ('HUSBAND', 'Husband'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('LEGAL GUARDIAN', 'Legal Guardian'), ('OTHER', 'Other')], max_length=20)),
                ('other_relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin_contacts', to='submission.Submission')),
            ],
        ),
    ]
