# Generated by Django 3.0.4 on 2020-04-04 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20200404_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='patient_photos')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_photo', to='submission.Submission')),
            ],
        ),
    ]
