# Generated by Django 3.0.4 on 2020-04-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_nextofkincontact'),
        ('submission', '0004_patientphoto'),
    ]

    operations = [
    ]
