# Generated by Django 3.0.4 on 2020-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='identifier',
            field=models.CharField(max_length=50),
        ),
    ]
