# Generated by Django 3.0.4 on 2020-03-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('submission', '0005_auto_20200328_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonalData',
        ),
    ]
