# Generated by Django 3.0.4 on 2020-03-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('submission', '0006_auto_20200328_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='master',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='submission.Submission'),
        ),
    ]
