# Generated by Django 3.0.4 on 2020-03-28 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_commonsymptoms_gradedsymptoms_overallwellbeing_relatedconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ChosenMedicalCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_center', to='submission.MedicalCenter')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_medical_center', to='submission.Submission')),
            ],
        ),
    ]
