# Generated by Django 3.0.4 on 2020-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_chosenmedicalcenter_medicalcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenterAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
