# Generated by Django 3.0.4 on 2020-03-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_medicalcenteradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submission.Patient'),
        ),
    ]
