# Generated by Django 3.0.4 on 2020-03-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20200328_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
