# Generated by Django 3.0.4 on 2020-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_delete_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_admitted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='severity',
            field=models.CharField(blank=True, choices=[('MIN', 'Minor'), ('MED', 'Medium'), ('MAJ', 'Major')], max_length=3, null=True),
        ),
    ]
