# Generated by Django 3.0.4 on 2020-03-29 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20200329_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_admitted',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='severity',
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
