# Generated by Django 3.0.5 on 2020-04-12 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('severity_match', models.CharField(blank=True, choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green')], max_length=6)),
                ('total', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bedtype_creator', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bedtype_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('equip fail', 'Equipment failure'), ('unavailable', 'Unavailable')], max_length=20, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Out of service'), (1, 'Assigned'), (2, 'Available')], default=2)),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='equipment.BedType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_creator', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bed_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
