# Generated by Django 3.0.4 on 2020-03-28 14:34

from django.db import migrations

from custom_auth.utils import get_user_model


def update_admin(apps, schema_editor):
    User = get_user_model()
    admin = User.objects.get(username='admin')
    admin.is_staff = True
    admin.set_password('352MaAehYJJu')
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_create_admin'),
    ]

    operations = [
        migrations.RunPython(update_admin)
    ]
