# Generated by Django 3.0.5 on 2020-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200419_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='modifier',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalPatient',
        ),
    ]
