# Generated by Django 3.0.6 on 2020-05-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='rel_data',
            field=models.TextField(null=True),
        ),
    ]
