# Generated by Django 3.0.6 on 2020-05-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0002_workflow_rel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='rel_data',
        ),
        migrations.AddField(
            model_name='workflow',
            name='rel_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='rel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
