# Generated by Django 3.0 on 2020-03-27 23:31

from django.db import migrations, models


def create_default(apps, schema_editor):
    Dummy = apps.get_model('dummy', 'Dummy')
    Dummy.objects.create(greeting='Hello', target='World')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_default)
    ]
